services:
  api-go:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  
    networks:
      - apinet

  api-python:
    build:
      context: ./remote/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  
    networks:
      - apinet

networks:
  apinet:  
